### ISSUE TITLE
Diacritic in table

### ISSUE THREAD

**Issue by FilipLukac** [Gregwar/RST#30]
Hello,
When Im tryin to create table with diacritic content, it fails and prints characters without diacritis.

It is possible to fix this ? Or any available solution

For example

```
=====  =====  ======
  Inputs     Output
------------  ------
 A      B    A or B
=====  =====  ======
Číslo  False  False
=====  =====  ======
```

prints:
?íslo T

**Comment by BlueM** [comment]
I stumbled upon this problem, too. @Gregwar: interested in a PR for this issue? (If yes, I’d need to know if you find it acceptable to add `symfony/polyfill-mbstring` to the dependencies, for installations where the mbstring extension is not available. Otherwise, the fix would only work with mbstring available and stick with the current problem, if not.)

**Comment by Gregwar** [comment]
Hello, I'm ok with that @BlueM, if you do a PR I will have a look

**Comment by BlueM** [comment]
Sorry it took that long …

**Comment by Gregwar** [comment]
It's merged
